import './style.css';
import * as THREE from 'three';
import { SceneController } from './scene';
import { UIController } from './ui';
import { RepoData } from './objects';

async function bootstrap() {
  const ui = new UIController(() => {
    scene.clearFocus();
  });
  
  const container = document.getElementById('canvas-container')!;
  const scene = new SceneController(container);
  
  // Set click callback
  scene.onSatelliteClick = (repo: RepoData) => {
    ui.showDetails(repo);
  };

  // Simulate loading steps for visual effect
  let progress = 0;
  const loadInterval = setInterval(() => {
    progress += Math.random() * 0.2;
    if (progress > 0.8) clearInterval(loadInterval);
    ui.updateLoading(Math.min(progress, 1));
  }, 150);

  try {
    // Fetch data generated by our github action/script
    const response = await fetch('/data/repos.json');
    if (!response.ok) throw new Error('Data not found');
    const repos: RepoData[] = await response.json();
    
    // Finish loading bar
    clearInterval(loadInterval);
    ui.updateLoading(1);
    
    // Init scene data
    setTimeout(() => {
      scene.initData(repos);
      ui.showHUD();
      document.getElementById('status-text')!.textContent = 'SYSTEM ONLINE';
    }, 500);

  } catch (error) {
    console.error("Failed to load repo data:", error);
    clearInterval(loadInterval);
    ui.updateLoading(1);
    setTimeout(() => {
      ui.showHUD();
      document.getElementById('status-text')!.textContent = 'DATA OFFLINE';
      document.getElementById('status-indicator')!.querySelector('.bg-cyan-500')?.classList.replace('bg-cyan-500', 'bg-red-500');
      document.getElementById('status-indicator')!.querySelector('.bg-cyan-400')?.classList.replace('bg-cyan-400', 'bg-red-400');
    }, 500);
  }

  // Animation Loop
  const clock = new THREE.Clock();
  
  function animate() {
    requestAnimationFrame(animate);
    const elapsedTime = clock.getElapsedTime();
    scene.update(elapsedTime);
  }

  animate();
}

(window as any).THREE = THREE;

bootstrap();
