import './style.css';
import * as THREE from 'three';
import { SceneController } from './scene';
import { UIController } from './ui';
import { RepoData } from './objects';

async function bootstrap() {
  let currentFocusIndex = -1;
  const ui = new UIController(() => {
    scene.resetView();
    currentFocusIndex = -1;
  });
  
  const container = document.getElementById('canvas-container')!;
  const scene = new SceneController(container);
  
  // Set click callback
  scene.onSatelliteClick = (repo: RepoData) => {
    ui.showDetails(repo);
  };

  // Simulate loading steps for visual effect
  let progress = 0;
  const loadInterval = setInterval(() => {
    progress += Math.random() * 0.2;
    if (progress > 0.8) clearInterval(loadInterval);
    ui.updateLoading(Math.min(progress, 1));
  }, 150);

  try {
    // Fetch data generated by our github action/script
    const response = await fetch('./data/repos.json');
    if (!response.ok) throw new Error('Data not found');
    const repos: RepoData[] = await response.json();
    
    // Finish loading bar
    clearInterval(loadInterval);
    ui.updateLoading(1);
    
    // Init scene data
    setTimeout(() => {
      scene.initData(repos);
      ui.showHUD();
      document.getElementById('status-text')!.textContent = 'SYSTEM ONLINE';
    }, 500);

  } catch (error) {
    console.error("Failed to load repo data:", error);
    clearInterval(loadInterval);
    ui.updateLoading(1);
    setTimeout(() => {
      ui.showHUD();
      document.getElementById('status-text')!.textContent = 'DATA OFFLINE';
      document.getElementById('status-indicator')!.querySelector('.bg-cyan-500')?.classList.replace('bg-cyan-500', 'bg-red-500');
      document.getElementById('status-indicator')!.querySelector('.bg-cyan-400')?.classList.replace('bg-cyan-400', 'bg-red-400');
    }, 500);
  }

  // Keyboard navigation
  window.addEventListener('keydown', (e) => {
    if (!scene.orbitalSystem || scene.orbitalSystem.satellites.length === 0) return;
    
    const sats = scene.orbitalSystem.satellites;
    const total = sats.length;
    
    if (e.key === 'ArrowRight' || e.key === 'd' || e.key === 'D') {
      currentFocusIndex = (currentFocusIndex + 1) % total;
      focusSatellite(currentFocusIndex);
    } else if (e.key === 'ArrowLeft' || e.key === 'a' || e.key === 'A') {
      currentFocusIndex = (currentFocusIndex - 1 + total) % total;
      focusSatellite(currentFocusIndex);
    } else if (e.key === 'Enter') {
      if (currentFocusIndex >= 0 && currentFocusIndex < total) {
         const repo = sats[currentFocusIndex].userData.repo;
         window.open(repo.url, '_blank');
      }
    } else if (e.key === 'Escape') {
      scene.resetView();
      ui.hideDetails();
      currentFocusIndex = -1;
    }
  });

  function focusSatellite(index: number) {
    const sats = scene.orbitalSystem!.satellites;
    const sat = sats[index];
    scene.focusedSatellite = sat;
    scene.focusedOffsetDist = 5;
    ui.showDetails(sat.userData.repo);
  }

  // Animation Loop
  const clock = new THREE.Clock();
  
  function animate() {
    requestAnimationFrame(animate);
    const elapsedTime = clock.getElapsedTime();
    scene.update(elapsedTime);
  }

  animate();
}

(window as any).THREE = THREE;

bootstrap();
